### ISSUE TITLE
Run Build Issue

### ISSUE THREAD

**Issue by vfernandes0408** [bitmovin/bitmovin-player-analytics-conviva#31]
I try to use develop and master version to run build but show error.

src/ts/AdExperienceTrackingPlugin.ts:2:38 - error TS2305: Module '"../../node_modules/bitmovin-player/bitmovinplayer"' has no exported member 'VastAdData'.
2 import { AdBreak, AdEvent, LinearAd, VastAdData } from 'bitmovin-player';                                       ~~~~~~~~~~
src/ts/AdExperienceTrackingPlugin.ts:31:29 - error TS2339: Property 'data' does not exist on type 'Ad'.
31     const adData = event.ad.data as VastAdData;                               ~~~~
src/ts/Html5Timer.ts:9:11 - error TS2367: This condition will always return 'true' since the types 'Timeout' and 'number' have no overlap.
9       if (timerId !== -1) {
            ~~~~~~~~~~~~~~
src/ts/Html5Timer.ts:11:9 - error TS2322: Type '-1' is not assignable to type 'Timeout'.
11         timerId = -1;
           ~~~~~~~


Found 4 errors.

**Comment by stonko1994** [comment]
- did you run `npm install` before?
- which command are you using to build?

**Comment by vfernandes0408** [comment]
Yes, i run npm install and after try to run npm build.

**Comment by stonko1994** [comment]
Did you change the version of the `bitmovin-player`?

From the error message it feels like an outdated `bitmovin-player` version. But that shouldn't be on the `develop` and `master` branch.

**Comment by vfernandes0408** [comment]
I tried with both version. I will try today again.

**Comment by jamesdavidholding** [comment]
Issue closed - if Still occurring please reopen through bitmovin support dashboard
