### ISSUE TITLE
The VST is not reported correctly 

### ISSUE THREAD

**Issue by ccordon01** [bitmovin/bitmovin-player-analytics-conviva#55]
The value I got in Touchstone from the VST is not accurate or even similar to the real value.

I guess this event could be a reason why we don't get the data correctly, or why this event is reported at the beginning of the session.

`this.playerStateManager.setPlayerState(Conviva.PlayerStateManager.PlayerState.STOPPED);`

**Comment by jamesdavidholding** [comment]
Issue closed as very old - if still occurring please raise through your support dashboard.
