### ISSUE TITLE
Make possible to override Html5Metadata default values

### ISSUE THREAD

**Issue by cristian-atehortua** [bitmovin/bitmovin-player-analytics-conviva#60]
In some cases, a user of this library could want to override the default values generated by Conviva in MetadataInterface. For example, if you are using Bitmovin in a LG Smart TV, you want to send *webOS* as "Operating System" and its version.

Currently, the only field that a user is able to override is "Device Category", can this be done for other values in Html5Interface?

It would be nice to have this feature for our integration of this Library in our LG Smart TV app.

Additional fields I think it would be nice to be overridden:
- Device Brand
- Device Manufacturer
- Device Model
- Device Type
- Device Version
- Operating System Name
- Operating System Version

**Comment by dweinber** [comment]
Implemented in https://github.com/bitmovin/bitmovin-player-analytics-conviva/pull/72 and released in [v4.0.3](https://github.com/bitmovin/bitmovin-player-analytics-conviva/releases/tag/v4.0.3)
